import type { StockItem } from "./logistique-types"

export const stockItemsInitiaux: StockItem[] = [
  {
    id: "1",
    cableType: "6FO",
    typeM: "M6",
    typeG: "G657",
    enroulement: "Touret",
    longueur: 1000,
  },
  {
    id: "2",
    cableType: "12FO",
    typeM: "M6",
    typeG: "G657",
    enroulement: "Touret",
    longueur: 2000,
  },
  {
    id: "3",
    cableType: "24FO",
    typeM: "M12",
    typeG: "G652",
    enroulement: "Touret",
    longueur: 1500,
  },
  {
    id: "4",
    cableType: "48FO",
    typeM: "M12",
    typeG: "G657",
    enroulement: "Touret",
    longueur: 3000,
  },
  {
    id: "5",
    cableType: "72FO",
    typeM: "M6",
    typeG: "G652",
    enroulement: "Couronne",
    longueur: 500,
  },
  {
    id: "6",
    cableType: "96FO",
    typeM: "M12",
    typeG: "G657",
    enroulement: "Touret",
    longueur: 2500,
  },
  {
    id: "7",
    cableType: "144FO",
    typeM: "M12",
    typeG: "G652",
    enroulement: "Touret",
    longueur: 1800,
  },
  {
    id: "8",
    cableType: "288FO",
    typeM: "M12",
    typeG: "G657",
    enroulement: "Couronne",
    longueur: 300,
  },
  {
    id: "9",
    cableType: "432FO",
    typeM: "M12",
    typeG: "G652",
    enroulement: "Touret",
    longueur: 1200,
  },
  {
    id: "10",
    cableType: "576FO",
    typeM: "M12",
    typeG: "G657",
    enroulement: "Touret",
    longueur: 800,
  },
  {
    id: "11",
    cableType: "764FO",
    typeM: "M12",
    typeG: "G652",
    enroulement: "Touret",
    longueur: 500,
  },
  {
    id: "12",
    cableType: "48FO",
    typeM: "M6",
    typeG: "G657",
    enroulement: "Couronne",
    longueur: 200,
  },
  {
    id: "13",
    cableType: "24FO",
    typeM: "M6",
    typeG: "G657",
    enroulement: "Couronne",
    longueur: 150,
  },
  {
    id: "14",
    cableType: "12FO",
    typeM: "M12",
    typeG: "G652",
    enroulement: "Couronne",
    longueur: 100,
  },
  {
    id: "15",
    cableType: "6FO",
    typeM: "M6",
    typeG: "G652",
    enroulement: "Couronne",
    longueur: 50,
  },
]
