import type { ContratMaintenance } from "./maintenance-types"

// Données initiales pour les contrats de maintenance
export const contratsInitiaux: ContratMaintenance[] = [
  {
    id: "contrat-1",
    client: "Entreprise ABC",
    reference: "MAINT-2023-001",
    type: "Annuel",
    montant: 1200,
    dateDebut: new Date(2023, 0, 15).toISOString(),
    dateEcheance: new Date(2024, 0, 14).toISOString(),
    statut: "Actif",
    description: "Maintenance des équipements informatiques",
    contactClient: "Jean Dupont",
    emailContact: "jean.dupont@abc.fr",
    telephoneContact: "01 23 45 67 89",
    notes: "Intervention sur site une fois par trimestre",
    dateCreation: new Date(2023, 0, 10).toISOString(),
    dateDerniereModification: new Date(2023, 0, 10).toISOString(),
  },
  {
    id: "contrat-2",
    client: "Société XYZ",
    reference: "MAINT-2023-002",
    type: "Mensuel",
    montant: 350,
    dateDebut: new Date(2023, 2, 1).toISOString(),
    dateEcheance: new Date(2024, 1, 29).toISOString(),
    statut: "Actif",
    description: "Maintenance du parc informatique et réseau",
    contactClient: "Marie Martin",
    emailContact: "m.martin@xyz.com",
    telephoneContact: "01 98 76 54 32",
    notes: "Support téléphonique 24/7 inclus",
    dateCreation: new Date(2023, 1, 15).toISOString(),
    dateDerniereModification: new Date(2023, 1, 15).toISOString(),
  },
  {
    id: "contrat-3",
    client: "Entreprise 123",
    reference: "MAINT-2023-003",
    type: "Trimestriel",
    montant: 600,
    dateDebut: new Date(2023, 3, 1).toISOString(),
    dateEcheance: new Date(2023, 11, 31).toISOString(),
    statut: "Expiré",
    description: "Maintenance des serveurs et sauvegardes",
    contactClient: "Pierre Durand",
    emailContact: "p.durand@123.fr",
    telephoneContact: "01 45 67 89 10",
    notes: "Renouvellement à discuter",
    dateCreation: new Date(2023, 2, 20).toISOString(),
    dateDerniereModification: new Date(2023, 2, 20).toISOString(),
  },
  {
    id: "contrat-4",
    client: "Groupe DEF",
    reference: "MAINT-2023-004",
    type: "Annuel",
    montant: 2400,
    dateDebut: new Date(2023, 5, 1).toISOString(),
    dateEcheance: new Date(2024, 4, 31).toISOString(),
    statut: "Actif",
    description: "Maintenance complète infrastructure IT",
    contactClient: "Sophie Leroy",
    emailContact: "s.leroy@def-groupe.com",
    telephoneContact: "01 23 45 67 89",
    notes: "Inclut 10h d'intervention sur site par mois",
    dateCreation: new Date(2023, 4, 15).toISOString(),
    dateDerniereModification: new Date(2023, 4, 15).toISOString(),
  },
  {
    id: "contrat-5",
    client: "Cabinet Juridique LMN",
    reference: "MAINT-2023-005",
    type: "Semestriel",
    montant: 900,
    dateDebut: new Date(2023, 6, 1).toISOString(),
    dateEcheance: new Date(2023, 11, 31).toISOString(),
    statut: "En attente",
    description: "Maintenance des postes de travail et logiciels métier",
    contactClient: "Alexandre Petit",
    emailContact: "a.petit@lmn-legal.fr",
    telephoneContact: "01 87 65 43 21",
    notes: "En attente de signature",
    dateCreation: new Date(2023, 5, 20).toISOString(),
    dateDerniereModification: new Date(2023, 5, 20).toISOString(),
  },
  {
    id: "contrat-6",
    client: "Clinique Santé+",
    reference: "MAINT-2023-006",
    type: "Annuel",
    montant: 3600,
    dateDebut: new Date(2023, 1, 1).toISOString(),
    dateEcheance: new Date(2024, 0, 31).toISOString(),
    statut: "Actif",
    description: "Maintenance des équipements médicaux informatisés",
    contactClient: "Dr. Isabelle Blanc",
    emailContact: "i.blanc@cliniquesanteplus.fr",
    telephoneContact: "01 23 45 67 89",
    notes: "Intervention prioritaire sous 4h",
    dateCreation: new Date(2023, 0, 15).toISOString(),
    dateDerniereModification: new Date(2023, 0, 15).toISOString(),
  },
  {
    id: "contrat-7",
    client: "Restaurant Le Gourmet",
    reference: "MAINT-2023-007",
    type: "Mensuel",
    montant: 150,
    dateDebut: new Date(2023, 3, 1).toISOString(),
    dateEcheance: new Date(2023, 8, 30).toISOString(),
    statut: "Résilié",
    description: "Maintenance du système de caisse et réservation",
    contactClient: "Michel Dubois",
    emailContact: "m.dubois@legourmet.fr",
    telephoneContact: "01 98 76 54 32",
    notes: "Contrat résilié suite à changement de prestataire",
    dateCreation: new Date(2023, 2, 15).toISOString(),
    dateDerniereModification: new Date(2023, 7, 10).toISOString(),
  },
  {
    id: "contrat-8",
    client: "École Supérieure",
    reference: "MAINT-2023-008",
    type: "Annuel",
    montant: 1800,
    dateDebut: new Date(2023, 8, 1).toISOString(),
    dateEcheance: new Date(2024, 7, 31).toISOString(),
    statut: "Actif",
    description: "Maintenance du parc informatique et réseau",
    contactClient: "François Martin",
    emailContact: "f.martin@ecole-sup.fr",
    telephoneContact: "01 45 67 89 10",
    notes: "Intervention pendant les vacances scolaires privilégiée",
    dateCreation: new Date(2023, 7, 15).toISOString(),
    dateDerniereModification: new Date(2023, 7, 15).toISOString(),
  },
]
